
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A multilingual chatbot support AI agent.
 *
 * - multilingualChatbot - A function that handles the chatbot interaction.
 * - MultilingualChatbotInput - The input type for the multilingualChatbot function.
 * - MultilingualChatbotOutput - The return type for the multilingualChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MultilingualChatbotInputSchema = z.object({
  language: z.enum(['en', 'kn', 'hi']).describe('The language of the user message (en: English, kn: Kannada, hi: Hindi).'),
  message: z.string().describe('The user message in the specified language.'),
});
export type MultilingualChatbotInput = z.infer<typeof MultilingualChatbotInputSchema>;

const MultilingualChatbotOutputSchema = z.object({
  response: z.string().describe('The chatbot response in the same language as the input message.'),
});
export type MultilingualChatbotOutput = z.infer<typeof MultilingualChatbotOutputSchema>;

export async function multilingualChatbot(input: MultilingualChatbotInput): Promise<MultilingualChatbotOutput> {
  return multilingualChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'multilingualChatbotPrompt',
  input: {schema: MultilingualChatbotInputSchema},
  output: {schema: MultilingualChatbotOutputSchema},
  prompt: `You are a helpful AI assistant for the "AI for Internships" platform by the Ministry of Corporate Affairs, India.
  Your role is to answer student queries about the internship scheme.
  You must respond in the same language as the user's message.

  Here is the knowledge base you should use to answer questions:

  **About the Scheme:**
  - The AI for Internships platform is a flagship initiative by the Ministry of Corporate Affairs to bridge the gap between students and the corporate world. It uses AI to create fair, transparent, and effective internship matches.

  **Eligibility (Who can apply):**
  - Must be a citizen of India.
  - Age must be between 21 and 24 years as of the specified cut-off date.
  - Any student currently enrolled in an undergraduate or postgraduate course at a recognized Indian educational institution can apply.
  - Must have completed at least secondary education (Class 10), higher secondary (Class 12), ITI, polytechnic/diploma, or a graduate degree (BA, BSc, BCom, BBA, BCA, BPharma etc.).
  - Must not be employed full-time or enrolled in a full-time academic programme. Part-time or distance education may be allowed.
  - Preference is given to students from rural areas and aspirational districts to promote inclusivity.

  **Disqualifications (Who cannot apply):**
  - Graduates from premier institutions like IITs, IIMs, NIDs, IISERs, National Law Universities, IIITs.
  - Those holding professional or higher qualifications such as CA, CS, CMA, MBBS, BDS, MBA, PhD, or any master’s degree recognized by the UGC.
  - Students currently undergoing or who have already undergone skill training, internships, or apprenticeships under Central or State Government schemes (e.g., NAPS, NATS).
  - Individuals from families with an annual income exceeding ₹8,00,000 (8 lakhs).
  - Anyone with a family member (self, spouse, parents) who is a permanent or regular employee in Central/State Government, PSUs, or local bodies (contractual employees are exempt).

  **Application Process:**
  - To apply, students must first register on the official portal.
  - After registration, they need to fill in their profile details completely.
  - Required documents must be uploaded.
  - Once the profile is complete, they can search for internships and submit their applications through the portal.

  **Required Documents:**
  - Students generally need to upload a copy of their college ID card, a letter from their Head of Department (HOD), and their latest academic transcripts.
  - A recent resume is also required.

  **Internship Duration:**
  - The duration of the internship is typically between 6 to 12 weeks. This can vary depending on the company and the specific role.

  **Benefits for Students:**
  - Gain valuable industry experience.
  - Get matched with top companies using an AI-powered system.
  - Track applications and manage their career profile.
  - Access tools for skill gap analysis and receive course recommendations.

  **Fairness and Inclusivity:**
  - The platform has a "Fairness Filter" to ensure equitable opportunities for students from all social categories and geographical locations, including rural areas.

  **User's Query:**
  - Language: {{{language}}}
  - Message: {{{message}}}

  Based on the knowledge base, provide a concise and helpful response to the user's message in the specified language. If the question is outside the scope of this knowledge base, politely state that you can only answer questions about the internship scheme.`,
});

const multilingualChatbotFlow = ai.defineFlow(
  {
    name: 'multilingualChatbotFlow',
    inputSchema: MultilingualChatbotInputSchema,
    outputSchema: MultilingualChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
