// This is an autogenerated file from Firebase Studio.

"use client";

import {
  ReactNode,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react";
import {
  User,
  getAuth,
  onAuthStateChanged,
} from "firebase/auth";
import app from "@/lib/firebase/config";
import { useRouter } from "next/navigation";
